version: "3.8"
services:
  web:
    image: pheanix/nginx-web:v2
    labels:
      description: Has simple web page.
    ports:
      - "9998:80"

  ghost:
    image: ghost:3-alpine
    deploy:
      replicas: 5
      placement:
        max_replicas_per_node: 1
    restart: always
    ports:
      - "9997:2368"
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      #url: http://192.168.77.105:9997

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 9996:8080
