CREATE TABLE IF NOT EXISTS result(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    StudentID INT,
    Task1 VARCHAR(255) NOT NULL,
	Task2 VARCHAR(255) NOT NULL,
    Task3 VARCHAR(255) NOT NULL,
	Task4 VARCHAR(255) NOT NULL	
) ENGINE=INNODB;
